---
sidebar: sidebar 
permalink: trident-use/backend_options.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, kubectl, tridentctl, backend management options 
summary: 了解在Trident中管理后端的不同方法。 
---
= 在后端管理选项之间移动
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解在Trident中管理后端的不同方法。



== 用于管理后端的选项

随着的推出 `TridentBackendConfig`，管理员现在可以通过两种独特的方式管理后端。这会提出以下问题：

* 使用创建的后端是否 `tridentctl`可通过进行管理 `TridentBackendConfig`？
* 是否可以使用管理 `tridentctl`使用创建的后端 `TridentBackendConfig`？




== 使用管理 `tridentctl`后端 `TridentBackendConfig`

本节介绍通过创建对象直接通过Kubenetes界面创建后端所需的管理步骤 `tridentctl`。 `TridentBackendConfig`

这适用于以下情形：

* 已有的后端，因为它们是使用创建的，所以 `tridentctl`没有 `TridentBackendConfig`。
* 使用创建的新后端 `tridentctl`，而存在其他 `TridentBackendConfig`对象。


在这两种情况下、都将继续存在后端、Trident会为这些后端计划卷并在其上运行。管理员可以选择以下两种方式之一：

* 继续使用以管理使用 `tridentctl`它创建的后端。
* 将使用创建的后端绑定 `tridentctl`到新 `TridentBackendConfig`对象。这样做意味着后端将使用而不是 `tridentctl`进行管理 `kubectl`。


要使用管理已有的后端 `kubectl`，您需要创建 `TridentBackendConfig`绑定到现有后端的。下面简要介绍了它的工作原理：

. 创建 Kubernetes 机密。此密钥包含Trident与存储集群/服务通信所需的凭据。
. 创建 `TridentBackendConfig`对象。其中包含有关存储集群 / 服务的详细信息，并引用了上一步中创建的密钥。必须注意指定相同的配置参数(如 `spec.backendName`、、 `spec.storagePrefix` `spec.storageDriverName`等)。 `spec.backendName`必须设置为现有后端的名称。




=== 第 0 步：确定后端

要创建 `TridentBackendConfig`绑定到现有后端的、您需要获取后端配置。在此示例中，假设已使用以下 JSON 定义创建了后端：

[listing]
----
tridentctl get backend ontap-nas-backend -n trident
+---------------------+----------------+--------------------------------------+--------+---------+
|          NAME       | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+---------------------+----------------+--------------------------------------+--------+---------+
| ontap-nas-backend   | ontap-nas      | 52f2eb10-e4c6-4160-99fc-96b3be5ab5d7 | online |      25 |
+---------------------+----------------+--------------------------------------+--------+---------+
----
[listing]
----
cat ontap-nas-backend.json
----
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.10.10.1",
  "dataLIF": "10.10.10.2",
  "backendName": "ontap-nas-backend",
  "svm": "trident_svm",
  "username": "cluster-admin",
  "password": "admin-password",
  "defaults": {
    "spaceReserve": "none",
    "encryption": "false"
  },
  "labels": {
    "store": "nas_store"
  },
  "region": "us_east_1",
  "storage": [
    {
      "labels": {
        "app": "msoffice",
        "cost": "100"
      },
      "zone": "us_east_1a",
      "defaults": {
        "spaceReserve": "volume",
        "encryption": "true",
        "unixPermissions": "0755"
      }
    },
    {
      "labels": {
        "app": "mysqldb",
        "cost": "25"
      },
      "zone": "us_east_1d",
      "defaults": {
        "spaceReserve": "volume",
        "encryption": "false",
        "unixPermissions": "0775"
      }
    }
  ]
}
----


=== 第 1 步：创建 Kubernetes 机密

创建一个包含后端凭据的机密，如以下示例所示：

[listing]
----
cat tbc-ontap-nas-backend-secret.yaml
----
[source, yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: ontap-nas-backend-secret
type: Opaque
stringData:
  username: cluster-admin
  password: admin-password
----
[listing]
----
kubectl create -f tbc-ontap-nas-backend-secret.yaml -n trident
secret/backend-tbc-ontap-san-secret created
----


=== 第2步：创建 `TridentBackendConfig`CR

下一步是创建 `TridentBackendConfig`将自动绑定到已有的CR `ontap-nas-backend` (如本示例所示)。确保满足以下要求：

* 中定义了相同的后端名称 `spec.backendName`。
* 配置参数与原始后端相同。
* 虚拟池(如果存在)必须与原始后端的顺序相同。
* 凭据通过 Kubernetes Secret 提供，而不是以纯文本形式提供。


在这种情况下、 `TridentBackendConfig`将如下所示：

[listing]
----
cat backend-tbc-ontap-nas.yaml
----
[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: tbc-ontap-nas-backend
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: 10.10.10.1
  dataLIF: 10.10.10.2
  backendName: ontap-nas-backend
  svm: trident_svm
  credentials:
    name: mysecret
  defaults:
    spaceReserve: none
    encryption: 'false'
  labels:
    store: nas_store
  region: us_east_1
  storage:
  - labels:
      app: msoffice
      cost: '100'
    zone: us_east_1a
    defaults:
      spaceReserve: volume
      encryption: 'true'
      unixPermissions: '0755'
  - labels:
      app: mysqldb
      cost: '25'
    zone: us_east_1d
    defaults:
      spaceReserve: volume
      encryption: 'false'
      unixPermissions: '0775'
----
[listing]
----
kubectl create -f backend-tbc-ontap-nas.yaml -n trident
tridentbackendconfig.trident.netapp.io/tbc-ontap-nas-backend created
----


=== 第3步：验证CR的状态 `TridentBackendConfig`

创建后 `TridentBackendConfig`，其阶段必须为 `Bound`。它还应反映与现有后端相同的后端名称和 UUID 。

[listing]
----
kubectl get tbc tbc-ontap-nas-backend -n trident
NAME                   BACKEND NAME          BACKEND UUID                           PHASE   STATUS
tbc-ontap-nas-backend  ontap-nas-backend     52f2eb10-e4c6-4160-99fc-96b3be5ab5d7   Bound   Success

#confirm that no new backends were created (i.e., TridentBackendConfig did not end up creating a new backend)
tridentctl get backend -n trident
+---------------------+----------------+--------------------------------------+--------+---------+
|          NAME       | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+---------------------+----------------+--------------------------------------+--------+---------+
| ontap-nas-backend   | ontap-nas      | 52f2eb10-e4c6-4160-99fc-96b3be5ab5d7 | online |      25 |
+---------------------+----------------+--------------------------------------+--------+---------+
----
现在、可以使用对象完全管理后端 `tbc-ontap-nas-backend` `TridentBackendConfig`。



== 使用管理 `TridentBackendConfig`后端 `tridentctl`

 `tridentctl`可用于列出使用创建的后端 `TridentBackendConfig`。此外，管理员还可以选择通过删除并确保 `spec.deletionPolicy`将设置为 `retain`来 `TridentBackendConfig`完全管理此类后端 `tridentctl`。



=== 第 0 步：确定后端

例如，假设以下后端是使用创建的 `TridentBackendConfig`：

[listing]
----
kubectl get tbc backend-tbc-ontap-san -n trident -o wide
NAME                    BACKEND NAME        BACKEND UUID                           PHASE   STATUS    STORAGE DRIVER   DELETION POLICY
backend-tbc-ontap-san   ontap-san-backend   81abcb27-ea63-49bb-b606-0a5315ac5f82   Bound   Success   ontap-san        delete

tridentctl get backend ontap-san-backend -n trident
+-------------------+----------------+--------------------------------------+--------+---------+
|       NAME        | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------+----------------+--------------------------------------+--------+---------+
| ontap-san-backend | ontap-san      | 81abcb27-ea63-49bb-b606-0a5315ac5f82 | online |      33 |
+-------------------+----------------+--------------------------------------+--------+---------+
----
从输出中可以看出、 `TridentBackendConfig`已成功创建并绑定到后端[观察后端的UUID]。



=== 步骤1：确认 `deletionPolicy`设置为 `retain`

让我们来看看的价值 `deletionPolicy`。需要将其设置为 `retain`。这样可以确保在删除CR时 `TridentBackendConfig`，后端定义仍然存在，并且可以使用进行管理 `tridentctl`。

[listing]
----
kubectl get tbc backend-tbc-ontap-san -n trident -o wide
NAME                    BACKEND NAME        BACKEND UUID                           PHASE   STATUS    STORAGE DRIVER   DELETION POLICY
backend-tbc-ontap-san   ontap-san-backend   81abcb27-ea63-49bb-b606-0a5315ac5f82   Bound   Success   ontap-san        delete

# Patch value of deletionPolicy to retain
kubectl patch tbc backend-tbc-ontap-san --type=merge -p '{"spec":{"deletionPolicy":"retain"}}' -n trident
tridentbackendconfig.trident.netapp.io/backend-tbc-ontap-san patched

#Confirm the value of deletionPolicy
kubectl get tbc backend-tbc-ontap-san -n trident -o wide
NAME                    BACKEND NAME        BACKEND UUID                           PHASE   STATUS    STORAGE DRIVER   DELETION POLICY
backend-tbc-ontap-san   ontap-san-backend   81abcb27-ea63-49bb-b606-0a5315ac5f82   Bound   Success   ontap-san        retain
----

NOTE: 除非将设置为， `retain`否则请勿继续下一步 `deletionPolicy`。



=== 第2步：删除 `TridentBackendConfig`CR

最后一步是删除 `TridentBackendConfig`CR。确认已设置为 `retain`后 `deletionPolicy`，您可以继续删除：

[listing]
----
kubectl delete tbc backend-tbc-ontap-san -n trident
tridentbackendconfig.trident.netapp.io "backend-tbc-ontap-san" deleted

tridentctl get backend ontap-san-backend -n trident
+-------------------+----------------+--------------------------------------+--------+---------+
|       NAME        | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------+----------------+--------------------------------------+--------+---------+
| ontap-san-backend | ontap-san      | 81abcb27-ea63-49bb-b606-0a5315ac5f82 | online |      33 |
+-------------------+----------------+--------------------------------------+--------+---------+
----
删除对象后 `TridentBackendConfig`、Trident会直接将其删除、而不会实际删除后端本身。
